// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAztMpEEBoF9Adnl2PEuEGo7qEOr1fqINE',
//     appId: '1:281465461068:web:e9a23c2dba58d5527897e9',
//     messagingSenderId: '281465461068',
//     projectId: 'flutter-project-2b85f',
//     authDomain: 'flutter-project-2b85f.firebaseapp.com',
//     storageBucket: 'flutter-project-2b85f.appspot.com',
//     measurementId: 'G-RSEBSK9TCR',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDA8ATJzKFkNcDHB_gF4Sj6WNrPWjGE-JI',
//     appId: '1:281465461068:android:72156fee5fd34d6e7897e9',
//     messagingSenderId: '281465461068',
//     projectId: 'flutter-project-2b85f',
//     storageBucket: 'flutter-project-2b85f.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCjguTV99xGoP3DqOsUMi9vRStdWjBa544',
//     appId: '1:281465461068:ios:999916682df8a7de7897e9',
//     messagingSenderId: '281465461068',
//     projectId: 'flutter-project-2b85f',
//     storageBucket: 'flutter-project-2b85f.appspot.com',
//     iosClientId: '281465461068-qajmnbdbkjj91gt8dji5ua1fjp0d2782.apps.googleusercontent.com',
//     iosBundleId: 'com.example.shop',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCjguTV99xGoP3DqOsUMi9vRStdWjBa544',
//     appId: '1:281465461068:ios:999916682df8a7de7897e9',
//     messagingSenderId: '281465461068',
//     projectId: 'flutter-project-2b85f',
//     storageBucket: 'flutter-project-2b85f.appspot.com',
//     iosClientId: '281465461068-qajmnbdbkjj91gt8dji5ua1fjp0d2782.apps.googleusercontent.com',
//     iosBundleId: 'com.example.shop',
//   );
// }
